// src/components/product_data.jsx

const product_data = {
    boltSeals: [
      {
        id: 1,
        product_name: "Bolt Seal 1",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/whitebolt.png'),
      },
      {
        id: 2,
        product_name: "Bolt Seal 2",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/yellowbolt2.png'),
      },
      {
        id: 3,
        product_name: "Bolt Seal 3",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/greenbolt.png'),
      },
      {
        id: 4,
        product_name: "Bolt Seal 4",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/bluebolt.png'),
      },
      {
        id: 5,
        product_name: "Bolt Seal 1",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/yellowbolt3.png'),
      },
      {
        id: 6,
        product_name: "Bolt Seal 2",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/whitebolt.png'),
      },
      {
        id: 7,
        product_name: "Bolt Seal 3",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/bluebolt.png'),
      },
      {
        id: 8,
        product_name: "Bolt Seal 4",
        description: "High-security bolt seal...",
        price: 100,
        currency: "GHC",
        thumb: require('../Media/greenbolt.png'),
      },
      
      // More bolt seals...
    ],
    cableSeals: [
      {
        id: 9,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/bluecable.png'),
      },
      {
        id: 10,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/orangecable.png'),
      },
      {
        id: 11,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/redcable.png'),
      },
      {
        id: 12,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/greencableseal.png'),
      },
      {
        id: 13,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/greencableseal.png'),
      },
      {
        id: 14,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/redcable.png'),
      },
      {
        id: 15,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/orangecable.png'),
      },
      {
        id: 16,
        product_name: "Cable Seal 1",
        description: "Durable cable seal...",
        price: 80,
        currency: "GHC",
        thumb: require('../Media/bluecable.png'),
      },
      // More cable seals...
    ],
    plasticSeals: [
      {
        id: 17,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/whiteplasticseal.png'),
      },
      {
        id: 18,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/greenplasticseal.png'),
      },
      {
        id: 19,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/blueplasticseal.png'),
      },
      {
        id: 20,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/yellowplasticseal.png'),
      },
      {
        id: 21,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/orangeplasticseal.png'),
      },
      {
        id: 22,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/orangeplasticseal.png'),
      },
      {
        id: 23,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/blueplasticseal.png'),
      },
      {
        id: 24,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/yellowplasticseal.png'),
      },
      {
        id: 25,
        product_name: "Plastic Seal 1",
        description: "Versatile plastic seal...",
        price: 150,
        currency: "GHC",
        thumb: require('../Media/whiteplasticseal.png'),
      },
      
      
      // More plastic seals...
    ],
  };
  
  export default product_data; // Make sure to export the data
  